### ISSUE TITLE
Is explicit IProperty necessary?

### ISSUE THREAD

**Issue by kanimaru** [LibraStack/UnityMvvmToolkit#34]
## Feature request

Wouldn't it be cool when you don't need the IProperty Interface manually. So that you just add a annotation to a field of your model object aka scriptable object. And the binder will create the Property for it and updates the model object itself. 

## Problem it solves

Currently I have something like that: 

```
    public class HoverData : ScriptableObject
    {
        public float height;
        public float power;
    }
```

And need an additional model object like:

```
    public class HoverModel : IBindingContext
    {
        public IProperty<float> Height { get; }  
        public IProperty<float> Power   { get; }

        public HoverModel(HoverData hoverData){
            Height = new Property<float>();
            Power = new Property<float>();

            Height.ValueChanged += (_, f) => hoverData.height = f;
            Power.ValueChanged += (_, f) => hoverData.power = f;
        }
    }
```

would be cool when we could do something like:

    public class HoverData : ScriptableObject
    {
        [Property]
        public float height;
        [Property]
        public float power;

       // And maybe also for commands?
       [Command]
       public void DoStuff() { }
    }

## Describe alternatives you've considered
-

## Additional information, screenshots, or code examples
-

Maybe I don't understand it correctly and you can show me a better way.

**Comment by ChebanovDD** [comment]
Right now you can [wrap a non-observable model](https://github.com/LibraStack/UnityMvvmToolkit#wrapping-a-non-observable-model).

```csharp
public class HoverData : ScriptableObject, IBindingContext
{
    [Observable(nameof(Power))]
    private readonly IProperty<float> _power = new Property<float>();

    [Observable(nameof(Height))]
    private readonly IProperty<float> _height = new Property<float>();

    public float Power
    {
        get => _power.Value;
        set => _power.Value = value;
    }

    public float Height
    {
        get => _height.Value;
        set => _height.Value = value;
    }
}
```

Is this what you are looking for?

**Comment by kanimaru** [comment]
That could work but still alot of overhead. I'll try my luck with the https://github.com/vovgou/loxodon-framework they have also MVVM for Unity. But thx for your reply.
