### ISSUE TITLE
Unknown type: 'UnityMvvmToolkit.UITK.BindableListView'

### ISSUE THREAD

**Issue by Creekmind** [LibraStack/UnityMvvmToolkit#59]
## Describe the bug

BindableListView doesn't work in the UI Toolkit.

## Minimal reproduction code and steps

1. Unity 2023.1.14f
2. UnityMvvmToolkit 1.1.8
3. I'm using manual for BindableListView - https://github.com/LibraStack/UnityMvvmToolkit/tree/c9b55759c90b16a5f2a1f8eea3bdb887a3df671a#bindablelistview
4. Create UI document with BindableListView
5. Start UI builder or application

## Current result

UI Builder:
![image](https://github.com/LibraStack/UnityMvvmToolkit/assets/3481215/f6eb0216-4570-40a3-b455-274c48604a3f)

Plus, there isn't such custom control in UI builder
![image](https://github.com/LibraStack/UnityMvvmToolkit/assets/3481215/c5c9ea04-9aad-46fe-8656-cb55c078df30)

## Expected result

BindableListView is working

## Additional information, screenshots, or code examples

View:
```xml
<ui:UXML xmlns:ui="UnityEngine.UIElements" xmlns:uie="UnityEditor.UIElements"
  xmlns:uitk="UnityMvvmToolkit.UITK"
  editor-extension-mode="False">

  <Style
    src="project://database/Assets/Art/UI/Character/Inventory.uss" />

  <ui:VisualElement name="Inventory" class="inventory" contentContainer="true">
    <uitk:BindableListView binding-items-source-path="Items" />
  </ui:VisualElement>
</ui:UXML>
```

Exception in Unity debug console:

```
Element 'UnityMvvmToolkit.UITK.BindableUIElements.BindableListView' has no registered factory method.
UnityEngine.UIElements.UIDocument:OnValidate () (at /Users/bokken/build/output/unity/unity/ModuleOverrides/com.unity.ui/Core/GameObjects/UIDocument.cs:708)

```

**Comment by ChebanovDD** [comment]
The [BindableListView](https://github.com/LibraStack/UnityMvvmToolkit#bindablelistview) example has been updated. Thanks.
